name: loja
description: "Desafio de Flutter"


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  go_router: ^14.3.0
  get_it: ^8.0.2
  shared_preferences: ^2.3.2
  connectivity_plus: ^3.0.3
  
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mocktail: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Instruction
      fonts:
        - asset: assets/fonts/Instruction_Bold_Italic.otf
          weight: 700
        - asset: assets/fonts/Instruction_Bold.otf
          weight: 700
        - asset: assets/fonts/Instruction_Italic.otf
          weight: 700
        - asset: assets/fonts/Instruction.otf
          weight: 700
  
